### ISSUE TITLE
Fix E* titles

### ISSUE THREAD

**Issue by Scrxtchy** [ilwaz/TachiyomiEH#23]
![image](https://user-images.githubusercontent.com/12771982/55662527-a8e18480-585f-11e9-9e9b-510ada36f62a.png)

Some results are now getting tags added to their titles

**Comment by Scrxtchy** [comment]
Might be a temporary change on their side, since I can't seem to trigger it again, and clearing the cached titles has helped.

But I wonder if I should pull in a patch for it anyway

**Comment by ilwaz** [comment]
I think it has to do with the new different modes. If you select "compact" on the website, it will list tags along side the titles. We need a way to select a specific mode (previous the app tried to choose dm_0, but now that is not an option)

**Comment by Scrxtchy** [comment]
Ahh, that would be it then

**Comment by Scrxtchy** [comment]
Shit would be absolutely broke if someone used thumbnail view
